version: "3"

services:
  db:
    image: mysql:latest
    container_name: stylish_adv
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "stylish_adv"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
    volumes:
      - ./stylish_backend_2022-02-23.sql:/init.sql
    
